### ISSUE TITLE
Make ScrollablePositionedList ItemScrollController extend ScrollController

### ISSUE THREAD

**Issue by nabil6391** [google/flutter.widgets#235]
## Problem description

Currently ScrollablePositionedList cannot utilise scrollController of typical ScrollViews, as a result we are unable to Utilise common code among them. For example, We cannot wrap the ScrollablePositionedList with a ScrollBar to show a scrollbar to the Listview.

It would be great if you can extend or utilise ItemScrollController to extend ScrollController

**Comment by mellowcello77** [comment]
Is there anyway to detect scroll direction, or do we need "scrollController" as in the problem description?

**Comment by thuchau** [comment]
I have a issue when wrap ScrollablePositionedList in Scrollbar.

The Scrollbar attempted to use the provided ScrollController. This ScrollController should be associated with the ScrollView that the Scrollbar is being applied to. When providing your own ScrollController, ensure both the Scrollbar and the Scrollable widget use the same one.

**Comment by khylenko** [comment]
Any news about old good ScrollController? 
How can i detect scroll and scroll extent without it?

**Comment by mattrltrent2** [comment]
Any updates? I need a CupertinoScrollBar to be able to work with this.

**Comment by nabil6391** [comment]
Till the PR that I have given not get merged, anyone who requires this can actually my forked repo to access the scrollController. Just have to do this in pubspec.yaml

```
scrollable_positioned_list:
    git:
      url: https://github.com/nabil6391/flutter.widgets.git
      ref: master
      path: packages/scrollable_positioned_list/
```
